services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: expense-tracker
    volumes:
      - mongodata:/data/db
      - mongoconfig:/data/configdb

volumes:
  mongodata:
  mongoconfig:
